Script started on 2023-10-05 14:18:47-04:00 [TERM="xterm-256color" TTY="/dev/pts/63" COLUMNS="80" LINES="24"]
]0;slee2883@compute:~/courses/cs2211/Asn/asn2[?2004h[slee2883@compute asn2]$ date
[?2004lThu Oct  5 02:18:50 PM EDT 2023
]0;slee2883@compute:~/courses/cs2211/Asn/asn2[?2004h[slee2883@compute asn2]$ pw[K[Kwhom[Kami
[?2004lslee2883
]0;slee2883@compute:~/courses/cs2211/Asn/asn2[?2004h[slee2883@compute asn2]$ pwd
[?2004l/home/slee2883/courses/cs2211/Asn/asn2
]0;slee2883@compute:~/courses/cs2211/Asn/asn2[?2004h[slee2883@compute asn2]$ ./[7mpower2_calculator[27mpower2_calculator
[?2004lEnter a non-negative integer exponent (0 to exit): 32
4294967296
Enter a non-negative integer exponent (0 to exit): 60
1152921504606846976
Enter a non-negative integer exponent (0 to exit): 63
9223372036854775808
Enter a non-negative integer exponent (0 to exit): 0
]0;slee2883@compute:~/courses/cs2211/Asn/asn2[?2004h[slee2883@compute asn2]$ exit
[?2004lexit

Script done on 2023-10-05 14:19:23-04:00 [COMMAND_EXIT_CODE="0"]
